name: Generate Sitemaps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run sitemap generator
        run: node generate.mjs

      - name: Upload sitemap output
        uses: actions/upload-artifact@v4
        with:
          name: sitemaps
          path: dist
