name: Generate language-specific sitemaps

on:
  schedule:
    - cron: '0 3 * * *'  # Dagelijks om 03:00 UTC
  workflow_dispatch:     # Manueel triggerbaar

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean previous node_modules (force fresh run)
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install node-fetch@2 xml2js

      - name: Run generate script
        run: node generate.mjs

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Auto-update sitemaps via GitHub Action"
          file_pattern: "dist/*.xml"
