name: Generate Sitemaps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run sitemap generator
        run: node generate.mjs

      - name: Upload sitemap output
        uses: actions/upload-artifact@v4
        with:
          name: sitemaps
          path: output/
